#!/bin/sh
#check if /var/lib/redis/dump.rdb is the good path to Redis dumps
cd /var/lib/redis && tar zcvf ~/config/redis/cron/$(date +%Y.%m.%d-%H.%M).tar.gz dump.rdb && cd ~/config/redis/cron && find . -type f -mtime +7 | xargs rm -f
